export const endPassDataMock = [
  {
    id: 1,
    title: "（1年期a）初级会计实务+经济法基础",
    category: "2022年中级会计职称考试",
    type: "单科",
    origin: "18",
    rate: "10",
    current: "18",
  },
  {
    id: 2,
    title: "（1年期b）初级会计实务+经济法基础",
    category: "2022年中级会计职称考试",
    type: "单科",
    origin: "18",
    rate: "10",
    current: "18",
  },
  {
    id: 3,
    title: "（1年期c）初级会计实务+经济法基础",
    category: "2022年中级会计职称考试",
    type: "单科",
    origin: "18",
    rate: "10",
    current: "18",
  },
  {
    id: 4,
    title: "（1年期d）初级会计实务+经济法基础",
    category: "2022年中级会计职称考试",
    type: "单科",
    origin: "18",
    rate: "10",
    current: "18",
  },
  {
    id: 5,
    title: "（1年期e）初级会计实务+经济法基础",
    category: "2022年中级会计职称考试",
    type: "单科",
    origin: "18",
    rate: "10",
    current: "18",
  },
];
